name: djangoflow_analytics
description: A library for tracking analytics with multiple Analytics providers in Flutter applications.
version: 0.1.0+1
homepage: https://github.com/djangoflow/flutter-djangoflow/tree/main/packages/djangoflow_analytics/djangoflow_analytics

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  analytics: ^2.0.3
  flutter:
    sdk: flutter

  # To update check https://github.com/dart-lang/mockito/issues/812
  mockito: 5.4.4

dev_dependencies:
  build_runner: any
  flutter_lints: any
  flutter_test:
    sdk: flutter
