name: djangoflow_app
description: A simple, opinionated, and minimal Flutter application structure for quick start and easy maintenance.
version: 6.0.1
homepage: https://github.com/djangoflow/flutter-djangoflow/tree/main/packages/djangoflow_app

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  dio: any
  flutter_bloc: any
  freezed_annotation: any
  hydrated_bloc: any
  json_annotation: any
  package_info_plus: any
  path_provider: any
  provider: any

dev_dependencies:
  bloc_test: any
  build_runner: any
  flutter_lints: any
  flutter_test:
    sdk: flutter
  freezed: any
  json_serializable: any
  mocktail: any
