name: djangoflow_remote_config
description: Djangoflow Remote Config is a library that helps to handle remote config in your flutter application.
version: 0.1.0+3
homepage: https://github.com/djangoflow/flutter-djangoflow/tree/main/packages/djangoflow_remote_config

environment:
  sdk: ">=3.1.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: any
  djangoflow_bloc_extensions: any
  djangoflow_openapi: any
  djangoflow_openapi_extensions: any
  flutter_bloc: any
  freezed_annotation: any
  hydrated_bloc: any
  json_annotation: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  freezed: any
  json_serializable: any
  build_runner: any
