name: djangoflow_facebook_analytics
description: A library provides an easy and organized way to implement Facebook Analytics for your Flutter apps.
version: 0.1.0+1
homepage: https://github.com/djangoflow/flutter-djangoflow/tree/main/packages/djangoflow_analytics/djangoflow_facebook_analytics
publish_to: none

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  analytics: ^2.0.3
  djangoflow_analytics:
    git:
      url: https://github.com/ccappflow/flutter-djangoflow
      path: packages/djangoflow_analytics/djangoflow_analytics
  facebook_app_events: ^0.19.4
  flutter:
    sdk: flutter
  # To update check https://github.com/dart-lang/mockito/issues/812
  mockito: 5.4.4

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
