name: djangoflow_openapi
version: 0.1.22
description: DjangoFlow OpenAPI API Client
homepage: https://github.com/djangoflow/flutter-djangoflow/

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  dio: any
  json_annotation: any

dev_dependencies:
  build_runner: any
  json_serializable: any
  test: any
