name: djangoflow_firebase_analytics
description: A library provides an easy and organized way to implement Firebase Analytics for your Flutter apps.
version: 0.3.0+1
homepage: https://github.com/djangoflow/flutter-djangoflow/

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  analytics: any
  djangoflow_analytics: any
  firebase_analytics: any
  firebase_analytics_platform_interface: any
  firebase_core: any
  flutter:
    sdk: flutter
  # To update check https://github.com/dart-lang/mockito/issues/812
  mockito: 5.4.4

dev_dependencies:
  build_runner: any
  flutter_lints: any
  flutter_test:
    sdk: flutter
