name: djangoflow_mixpanel_analytics
description: A library provides an easy and organized way to implement Mixpanel Analytics for your Flutter apps.
version: 0.5.0+1
homepage: https://github.com/djangoflow/flutter-djangoflow/tree/main/packages/djangoflow_analytics/djangoflow_mixpanel_analytics
publish_to: none

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  analytics: ^2.0.3
  djangoflow_analytics:
    git:
      url: https://github.com/ccappflow/flutter-djangoflow
      path: packages/djangoflow_analytics/djangoflow_analytics
  flutter:
    sdk: flutter
  mixpanel_flutter: any
  mockito: any

dev_dependencies:
  build_runner: any
  flutter_lints: any
  flutter_test:
    sdk: flutter
