name: djangoflow_mixpanel_analytics
description: A library provides an easy and organized way to implement Mixpanel Analytics for your Flutter apps.
version: 0.5.0+1
homepage: https://github.com/djangoflow/flutter-djangoflow/tree/main/packages/djangoflow_analytics/djangoflow_mixpanel_analytics

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  # Need to update
  analytics: any
  djangoflow_analytics: any
  flutter:
    sdk: flutter
  # need to update
  mixpanel_flutter: any
  # To update check https://github.com/dart-lang/mockito/issues/812
  mockito: 5.4.4

dev_dependencies:
  build_runner: any
  flutter_lints: any
  flutter_test:
    sdk: flutter
