name: djangoflow_auth
description: djangoflow_auth is your ultimate Flutter authentication companion, packed with Djangoflow API supports.
version: 0.6.0+1
homepage: https://github.com/djangoflow/flutter-djangoflow/tree/main/packages/djangoflow_auth/djangoflow_auth

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: any
  collection: any
  dio: any
  freezed_annotation: any
  hydrated_bloc: any
  universal_html: any
  uuid: any
  djangoflow_openapi:
    git:
      url: https://github.com/ccappflow/flutter-djangoflow
      path: packages/djangoflow_openapi

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  flutter_lints: any
  freezed: any
  json_serializable: any
  mocktail: any
