name: djangoflow_sentry_reporter
description: A library that allows you to report errors to `Sentry` using the `djangoflow_error_reporter` pacakge.
version: 0.3.0+1
homepage: https://github.com/djangoflow/flutter-djangoflow/tree/main/packages/djangoflow_error_reporters/djangoflow_sentry_reporter

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sentry_flutter: any
  djangoflow_error_reporter: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
