name: djangoflow_openapi_extensions
description: djangoflow_openapi_extensions is a Flutter package that empowers your Dio error handling in DjangoFlow OpenAPI projects with style and ease.
version: 0.0.3+4
homepage: https://github.com/djangoflow/flutter-djangoflow/tree/main/packages/djangoflow_openapi_extensions

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: any
  djangoflow_openapi: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
