name: djangoflow_auth_apple
description: djangoflow_auth_apple lets you embrace the magic of Apple Sign-In within your Flutter app!
version: 0.2.0+1
homepage: https://github.com/djangoflow/flutter-djangoflow/tree/main/packages/djangoflow_auth/djangoflow_auth_apple

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  djangoflow_auth: any
  sign_in_with_apple: any

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: any
